version: '3.8'

services:
 nextjs:
    build:
      context: .
    container_name: nextjs
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - DATABASE_URL=${DATABASE_URL}
